[project]
name = "target-databricks"
dynamic = [ "version" ]
description = "Singer target for Databricks, built with the Meltano Singer SDK"
authors = [{ name = "Meltano" }]
maintainers = [{ name = "Meltano" }]
requires-python = ">=3.13"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "ELT",
    "Databricks",
    "Delta Lake",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "singer-sdk~=0.54.7",
    "databricks-sql-connector>=4",
    "databricks-sdk>=0.145.0",
    "typing-extensions>=4.16.0",
]

[project.scripts]
target-databricks = "target_databricks.target:TargetDatabricks.cli"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pre-commit>=4",
    "pytest>=9",
    "pytest-xdist>=3.8.0",
    "ruff>=0.15",
    "singer-sdk[testing]",
    "tox>=4",
    "ty>=0.0.61",
    "types-jsonschema>=4.26.0.20260518",
]

[tool.uv]
default-groups = "all"

[build-system]
requires = [ "hatchling", "hatch-vcs" ]
build-backend = "hatchling.build"
